-- ============================================
-- Seed Data for Development/Testing
-- Optional: Run this to populate initial data
-- ============================================

-- Note: UUIDs should be generated by the application
-- These are example values for testing

-- ============================================
-- Create Default Admin User
-- ============================================
-- Password: Admin@123 (hashed with bcrypt, rounds=12)
-- In production, change this immediately!
INSERT OR IGNORE INTO users (id, email, password_hash, role, created_at, updated_at)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'admin@threatmodel.local',
  '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8ITeV1Y6R8Q0o0zZ.YK',
  'admin',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- ============================================
-- Create Test User
-- ============================================
-- Password: User@123
INSERT OR IGNORE INTO users (id, email, password_hash, role, created_at, updated_at)
VALUES (
  '00000000-0000-0000-0000-000000000002',
  'user@threatmodel.local',
  '$2b$12$8K1p/a0dL2LkKwSEhq2/cOdVD.z.L4lR7vM1NoQ2pKF0JT3jT8.Ha',
  'user',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- ============================================
-- Create Sample Threat Model
-- ============================================
INSERT OR IGNORE INTO threat_models (
  id,
  name,
  description,
  status,
  methodology,
  cloud_providers,
  system_description,
  created_by,
  created_at,
  updated_at
) VALUES (
  '10000000-0000-0000-0000-000000000001',
  'E-Commerce Platform',
  'Threat model for the main e-commerce web application',
  'in_progress',
  'STRIDE',
  '["AWS", "CloudFlare"]',
  'A multi-tier e-commerce application with web frontend, API backend, database, and payment processing integration.',
  '00000000-0000-0000-0000-000000000001',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- ============================================
-- Create Sample Threats
-- ============================================
INSERT OR IGNORE INTO threats (
  id,
  threat_model_id,
  category,
  name,
  description,
  severity,
  likelihood,
  impact,
  status,
  mitigation,
  created_at,
  updated_at
) VALUES
(
  '20000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000001',
  'spoofing',
  'User Account Takeover via Credential Stuffing',
  'Attackers may use leaked credentials from other breaches to gain unauthorized access to user accounts.',
  'high',
  'high',
  'high',
  'open',
  'Implement rate limiting, multi-factor authentication, and CAPTCHA on login endpoints. Monitor for suspicious login patterns.',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  '20000000-0000-0000-0000-000000000002',
  '10000000-0000-0000-0000-000000000001',
  'information_disclosure',
  'SQL Injection in Search API',
  'Search functionality may be vulnerable to SQL injection attacks, potentially exposing sensitive customer data.',
  'critical',
  'medium',
  'critical',
  'open',
  'Use parameterized queries and prepared statements for all database operations. Implement input validation and sanitization.',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  '20000000-0000-0000-0000-000000000003',
  '10000000-0000-0000-0000-000000000001',
  'tampering',
  'Price Manipulation in Shopping Cart',
  'Clients may be able to modify product prices before checkout by tampering with client-side data.',
  'high',
  'medium',
  'high',
  'open',
  'Implement server-side price validation. Never trust client-provided pricing data. Use cryptographic signatures for cart data.',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  '20000000-0000-0000-0000-000000000004',
  '10000000-0000-0000-0000-000000000001',
  'denial_of_service',
  'API Rate Limiting Bypass',
  'Attackers may overwhelm the API with requests, causing service degradation or outage.',
  'medium',
  'medium',
  'medium',
  'in_progress',
  'Implement distributed rate limiting using Redis. Add API gateway with DDoS protection. Monitor API metrics.',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- ============================================
-- Create Sample Compliance Mappings
-- ============================================
INSERT OR IGNORE INTO compliance_mappings (
  id,
  threat_id,
  framework,
  control_id,
  control_name,
  status,
  created_at,
  updated_at
) VALUES
(
  '30000000-0000-0000-0000-000000000001',
  '20000000-0000-0000-0000-000000000001',
  'NIST',
  'IA-2',
  'Identification and Authentication',
  'partially_implemented',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  '30000000-0000-0000-0000-000000000002',
  '20000000-0000-0000-0000-000000000002',
  'OWASP',
  'A03:2021',
  'Injection',
  'not_implemented',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  '30000000-0000-0000-0000-000000000003',
  '20000000-0000-0000-0000-000000000003',
  'PCI-DSS',
  '6.5.4',
  'Insecure Communications',
  'not_implemented',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- ============================================
-- Audit Log Initial Entry
-- ============================================
INSERT INTO audit_logs (
  user_id,
  action,
  resource_type,
  resource_id,
  details,
  timestamp
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  'SYSTEM_INIT',
  'database',
  NULL,
  'Database initialized with seed data',
  CURRENT_TIMESTAMP
);

-- ============================================
-- Verification Queries
-- ============================================
-- Uncomment to verify data was inserted

-- SELECT 'Users:' as table_name, COUNT(*) as count FROM users
-- UNION ALL
-- SELECT 'Threat Models:', COUNT(*) FROM threat_models
-- UNION ALL
-- SELECT 'Threats:', COUNT(*) FROM threats
-- UNION ALL
-- SELECT 'Compliance Mappings:', COUNT(*) FROM compliance_mappings
-- UNION ALL
-- SELECT 'Audit Logs:', COUNT(*) FROM audit_logs;
